/*
 * XKCD
 * Webcomic of romance, sarcasm, math, and language.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.Comic;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for InfoApi
 */
@Disabled
public class InfoApiTest {

    private static InfoApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new InfoApi(apiClient);
    }

    /**
     * Fetch comics and metadata  by comic id. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getByIdTest() throws ApiException {
        Double comicId = null;
        Comic response = api.getById(comicId)
                .execute();
        // TODO: test validations
    }

    /**
     * Fetch current comic and metadata. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getComicMetadataTest() throws ApiException {
        Comic response = api.getComicMetadata()
                .execute();
        // TODO: test validations
    }

}
